---
site_name: M. Shkrebtan
docs_dir: notes

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  logo: assets/photo-rembg.webp
  favicon: assets/photo-rembg.webp
  icon:
    repo: fontawesome/brands/github
  font: false
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  custom_dir: overrides

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mshkrebtan
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mshkrebtan/
    - icon: fontawesome/brands/square-lastfm
      link: https://www.last.fm/user/MShkrebtan

copyright: Copyright &copy; 2019–2023 Maksim Shkrebtan

plugins:
  - search:
      lang:
        - en
        - de
        - ru
  - tags:
      tags_file: index.md
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
  - awesome-pages

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
