---
site_name: M. Shkrebtan
repo_url: https://github.com/mshkrebtan/website
repo_name: mshkrebtan/website
docs_dir: notes
edit_uri: edit/mkdocs/notes/

theme:
  name: material
  logo: assets/photo.jpg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.top
  palette:
    primary: white
  custom_dir: overrides

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mshkrebtan
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mshkrebtan/
    - icon: fontawesome/brands/square-lastfm
      link: https://www.last.fm/user/MShkrebtan

copyright: Copyright &copy; 2019–2023 Maksim Shkrebtan

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
  - awesome-pages

markdown_extensions:
  - footnotes
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
